### ISSUE TITLE
0.0.1 doesn't work on M5Stack

### ISSUE THREAD

**Issue by unocerobits** [m5stack/M5Unit-Encoder#2]
Following the example, the value "-1" is always printed and the lights are not turned on.
Checking with WireScan example I saw 0x40 I2C address, so STM32 is alive.

Solution:
If you initialize I2C first, then it works perfectly.

`M5.begin(); `
**`Wire.begin(); `** <-- add this
`sensor.begin();`

Question:
Would be great to know the version of firmware of STM32, maybe is it not last? I'll try to update to 1.1

**Comment by TinyuZhao** [comment]
Thank you!
[Already fixed.](https://github.com/m5stack/M5Unit-Encoder/blob/2f703f0ba2d5fe58f927d3f8e4234469a406a744/examples/Unit_Encoder_M5Core/Unit_Encoder_M5Core.ino#L25)
